server:
  port: 8081

spring:
  application:
    name: project1

  datasource:
    url: jdbc:postgresql://localhost:5432/bookreader
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: mysecretkey123456789
  expiration: 3600000